
spring.application.name=CRBS
# ===============================
# =          SERVER
# ===============================
server.port=8080

# ===============================
# =       MYSQL CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/CRBS
spring.datasource.username=root
spring.datasource.password=naveen9950
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA) Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.data.mongodb.uri=mongodb://localhost:27017/CRBS
spring.data.mongodb.auto-index-creation=true


